### ISSUE TITLE
关于MVP的几点建议

### ISSUE THREAD

**Issue by daliyan** [PandaQAQ/PandaEye#3]
- 建议学习google的MVP范例，使用连接类去处理presenter 和 view的关联。这样逻辑更清楚
- 建议工程包应该按业务划分，不要presenter一个包 activity一个包，一个业务里面就包含MVP所有元素
- 建议独立一个data模块，里面用来获取数据（包括HTTP数据还是本地数据），这样逻辑更清楚。

**Comment by PandaQAQ** [comment]
感谢你的建议，后面会进行包结构的调整。
